//
// GENERATED — do not edit. Generated from the show-rule vectors every Treebars SDK is held to.
//
// The show rule, asked of this SDK.
//
// `inAppTriggerMatches` decides whether a message already on the device may be drawn by what
// just happened. The Android SDK and the web SDK answer the same vectors, and
// the filter half has a reference implementation whose answers are recorded beside each vector.
//
// Every case prints its answer on a `SHOWRULE` line. The FILTER half asserts: a `kind: event` case
// whose answer differs from the recorded one fails this test, after every line has printed. The
// TRIGGER half only reports, and the SDKs' answers are compared with each other. Content that does
// not decode answers false: a device never stores a message it cannot parse.
//

import XCTest
@testable import TreebarsSDK

final class InAppShowRuleConformanceTests: XCTestCase {

    func testAnswersEveryVectorAndAgreesWithTheReferenceOnTheFilterHalf() throws {
        // The dimension map column is what the SDK stamped on the event, read for a dimension row;
        // JSON null is an event with no map. The last column is the reference's recorded answer on
        // an event case, nil on a trigger kind.
        let vectors: [(String, String, String, String, String?, String, Bool?)] = [
        ("SR-001", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"immediate\"}}", "anything", "{}", nil, "null", nil),
        ("SR-002", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"immediate\"}}", "session_end", "{\"a\":1}", "Cart", "null", nil),
        ("SR-010", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"session_start\"}}", "session_start", "{}", nil, "null", nil),
        ("SR-011", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"session_start\"}}", "app_open", "{}", nil, "null", nil),
        ("SR-012", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"session_start\"}}", "app_foreground", "{}", nil, "null", nil),
        ("SR-020", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\",\"screen_name\":\"Cart\"}}", "screen_view", "{}", "Cart", "null", nil),
        ("SR-021", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\",\"screen_name\":\"Cart\"}}", "screen_view", "{\"screen_name\":\"Cart\"}", nil, "null", nil),
        ("SR-022", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\",\"screen_name\":\"Cart\"}}", "screen_view", "{\"name\":\"Cart\"}", nil, "null", nil),
        ("SR-023", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\",\"screen_name\":\"Cart\"}}", "screen_view", "{\"screen_name\":\"Checkout\"}", "Cart", "null", nil),
        ("SR-024", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\",\"screen_name\":\"Cart\"}}", "screen_view", "{}", "Checkout", "null", nil),
        ("SR-025", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\",\"screen_name\":\"Cart\"}}", "screen_view", "{}", "cart", "null", nil),
        ("SR-026", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\",\"screen_name\":\"Cart\"}}", "page_view", "{}", "Cart", "null", nil),
        ("SR-027", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\"}}", "screen_view", "{}", nil, "null", nil),
        ("SR-028", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\"}}", "screen_view", "{}", "Cart", "null", nil),
        ("SR-029", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"screen_view\",\"screen_name\":\"Cart\"}}", "purchase", "{\"screen_name\":\"Cart\"}", "Cart", "null", nil),
        ("SR-040", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\"}}", "purchase", "{}", nil, "null", true),
        ("SR-041", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\"}}", "add_to_cart", "{}", nil, "null", false),
        ("SR-042", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[]}}", "purchase", "{}", nil, "null", true),
        ("SR-050", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"pro\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", true),
        ("SR-051", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"pro\"}]}}", "purchase", "{\"plan\":\"free\"}", nil, "null", false),
        ("SR-052", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"eq\",\"value\":150}]}}", "purchase", "{\"value\":150}", nil, "null", true),
        ("SR-053", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"eq\",\"value\":150}]}}", "purchase", "{\"value\":\"150\"}", nil, "null", false),
        ("SR-054", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"eq\",\"value\":\"150\"}]}}", "purchase", "{\"value\":150}", nil, "null", true),
        ("SR-055", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"gift\",\"op\":\"eq\",\"value\":true}]}}", "purchase", "{\"gift\":true}", nil, "null", true),
        ("SR-056", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"gift\",\"op\":\"eq\",\"value\":true}]}}", "purchase", "{\"gift\":\"true\"}", nil, "null", true),
        ("SR-060", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"neq\",\"value\":\"pro\"}]}}", "purchase", "{\"plan\":\"free\"}", nil, "null", true),
        ("SR-061", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"neq\",\"value\":\"pro\"}]}}", "purchase", "{}", nil, "null", true),
        ("SR-062", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"neq\",\"value\":\"pro\"}]}}", "purchase", "{\"plan\":null}", nil, "null", true),
        ("SR-063", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"neq\",\"value\":\"pro\"}]}}", "purchase", "{\"plan\":\"\"}", nil, "null", true),
        ("SR-064", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"sku\",\"op\":\"not_contains\",\"value\":\"BC\"}]}}", "purchase", "{}", nil, "null", true),
        ("SR-065", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"not_in\",\"value\":\"[\\\"free\\\",\\\"pro\\\"]\"}]}}", "purchase", "{}", nil, "null", true),
        ("SR-066", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"coupon\",\"op\":\"not_exists\",\"value\":true}]}}", "purchase", "{}", nil, "null", true),
        ("SR-070", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"coupon\",\"op\":\"exists\"}]}}", "purchase", "{\"coupon\":\"SAVE10\"}", nil, "null", true),
        ("SR-071", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"coupon\",\"op\":\"exists\"}]}}", "purchase", "{}", nil, "null", false),
        ("SR-072", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"coupon\",\"op\":\"exists\"}]}}", "purchase", "{\"coupon\":null}", nil, "null", false),
        ("SR-073", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"coupon\",\"op\":\"exists\"}]}}", "purchase", "{\"coupon\":\"\"}", nil, "null", false),
        ("SR-074", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"exists\"}]}}", "purchase", "{\"value\":0}", nil, "null", true),
        ("SR-075", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"name\",\"op\":\"lt\",\"value\":\"m\"}]}}", "purchase", "{\"name\":\"\"}", nil, "null", false),
        ("SR-076", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"pro\"}]}}", "purchase", "{\"plan\":\"\"}", nil, "null", false),
        ("SR-080", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"sku\",\"op\":\"contains\",\"value\":\"BC\"}]}}", "purchase", "{\"sku\":\"ABC-1\"}", nil, "null", true),
        ("SR-081", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"sku\",\"op\":\"contains\",\"value\":\"BC\"}]}}", "purchase", "{\"sku\":\"XYZ-1\"}", nil, "null", false),
        ("SR-082", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"sku\",\"op\":\"contains\",\"value\":\"23\"}]}}", "purchase", "{\"sku\":12345}", nil, "null", true),
        ("SR-083", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"contains\",\"value\":15}]}}", "purchase", "{\"value\":\"150\"}", nil, "null", false),
        ("SR-090", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"gt\",\"value\":100}]}}", "purchase", "{\"value\":150}", nil, "null", true),
        ("SR-091", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"gt\",\"value\":100}]}}", "purchase", "{\"value\":5}", nil, "null", false),
        ("SR-092", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"gte\",\"value\":100}]}}", "purchase", "{\"value\":100}", nil, "null", true),
        ("SR-093", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"gt\",\"value\":100}]}}", "purchase", "{\"value\":\"150\"}", nil, "null", false),
        ("SR-094", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"gt\",\"value\":100}]}}", "purchase", "{\"value\":\"lots\"}", nil, "null", false),
        ("SR-095", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"version\",\"op\":\"gt\",\"value\":\"1.9\"}]}}", "purchase", "{\"version\":\"1.10\"}", nil, "null", false),
        ("SR-096", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"lt\",\"value\":100}]}}", "purchase", "{\"value\":5}", nil, "null", true),
        ("SR-097", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"lte\",\"value\":100}]}}", "purchase", "{\"value\":100}", nil, "null", true),
        ("SR-098", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"value\",\"op\":\"gt\",\"value\":100}]}}", "purchase", "{}", nil, "null", false),
        ("SR-099", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"gift\",\"op\":\"gt\",\"value\":0}]}}", "purchase", "{\"gift\":true}", nil, "null", false),
        ("SR-110", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"cart.size\",\"op\":\"gte\",\"value\":2}]}}", "purchase", "{\"cart\":{\"size\":3}}", nil, "null", false),
        ("SR-111", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"cart.size\",\"op\":\"gte\",\"value\":2}]}}", "purchase", "{\"cart\":{}}", nil, "null", false),
        ("SR-112", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"cart.size\",\"op\":\"gte\",\"value\":2}]}}", "purchase", "{\"cart.size\":3}", nil, "null", true),
        ("SR-120", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"pro\"},{\"key\":\"value\",\"op\":\"gt\",\"value\":100}]}}", "purchase", "{\"plan\":\"pro\",\"value\":150}", nil, "null", true),
        ("SR-121", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"pro\"},{\"key\":\"value\",\"op\":\"gt\",\"value\":100}]}}", "purchase", "{\"plan\":\"pro\",\"value\":5}", nil, "null", false),
        ("SR-130", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"\",\"op\":\"eq\",\"value\":\"\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", true),
        ("SR-131", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", true),
        ("SR-132", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"pro\"},{\"key\":\"\",\"op\":\"eq\",\"value\":\"\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", true),
        ("SR-133", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", true),
        ("SR-134", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":[]}]}}", "purchase", "{\"plan\":\"team\"}", nil, "null", true),
        ("SR-135", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":[null,null]}]}}", "purchase", "{\"plan\":\"team\"}", nil, "null", false),
        ("SR-140", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"matches_regex\",\"value\":\"^pro\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", false),
        ("SR-141", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"inactivity\",\"event_name\":\"purchase\"}}", "purchase", "{}", nil, "null", nil),
        ("SR-142", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\"}}", "purchase", "{}", nil, "null", false),
        ("SR-150", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[null]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", false),
        ("SR-151", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"op\":\"eq\",\"value\":\"pro\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", false),
        ("SR-152", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":7,\"op\":\"eq\",\"value\":\"pro\"}]}}", "purchase", "{\"7\":\"pro\"}", nil, "null", false),
        ("SR-153", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":\"plan\"}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", false),
        ("SR-154", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":[\"pro\"]}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", false),
        ("SR-155", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"exists\",\"value\":[\"pro\"]}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", true),
        ("SR-156", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"pro\",\"type\":\"colour\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", false),
        ("SR-157", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"exists\",\"type\":\"colour\"}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", false),
        ("SR-158", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"plan\",\"op\":\"eq\",\"value\":\"pro\",\"type\":null}]}}", "purchase", "{\"plan\":\"pro\"}", nil, "null", false),
        ("SR-159", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"amount\",\"op\":\"gte\",\"value\":0,\"type\":\"number\"}]}}", "purchase", "{\"amount\":\"42\\n\"}", nil, "null", false),
        ("SR-160", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"platform_type\",\"op\":\"eq\",\"value\":\"ios\"}]}}", "purchase", "{\"platform_type\":\"ios\"}", nil, "{\"platform_type\":\"android\"}", true),
        ("SR-161", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"platform_type\",\"op\":\"eq\",\"value\":\"ios\",\"source\":\"dimension\"}]}}", "purchase", "{\"platform_type\":\"ios\"}", nil, "{\"platform_type\":\"android\"}", false),
        ("SR-162", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"platform_type\",\"op\":\"eq\",\"value\":\"android\",\"source\":\"dimension\"}]}}", "purchase", "{\"platform_type\":\"ios\"}", nil, "{\"platform_type\":\"android\"}", true),
        ("SR-163", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"platform_type\",\"op\":\"eq\",\"value\":\"android\"}]}}", "purchase", "{\"platform_type\":\"android\"}", nil, "{\"platform_type\":\"ios\"}", true),
        ("SR-164", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"platform_type\",\"op\":\"eq\",\"value\":\"ios\",\"source\":\"device\"}]}}", "purchase", "{\"platform_type\":\"ios\"}", nil, "{\"platform_type\":\"ios\"}", false),
        ("SR-165", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"platform_type\",\"op\":\"neq\",\"value\":\"ios\",\"source\":\"device\"}]}}", "purchase", "{\"platform_type\":\"android\"}", nil, "{\"platform_type\":\"android\"}", false),
        ("SR-166", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"country\",\"op\":\"eq\",\"value\":\"DE\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"country\":\"DE\"}", false),
        ("SR-167", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"country\",\"op\":\"neq\",\"value\":\"DE\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{}", false),
        ("SR-168", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"region\",\"op\":\"eq\",\"value\":\"BE\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"region\":\"BE\"}", false),
        ("SR-169", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"city\",\"op\":\"neq\",\"value\":\"Berlin\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"city\":\"Berlin\"}", false),
        ("SR-170", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"carrier\",\"op\":\"neq\",\"value\":\"Vodafone\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"carrier\":\"Vodafone\"}", false),
        ("SR-171", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"platform_type\",\"op\":\"eq\",\"value\":\"ios\",\"source\":\"dimension\"}]}}", "purchase", "{\"platform_type\":\"ios\"}", nil, "null", false),
        ("SR-172", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"platform_type\",\"op\":\"neq\",\"value\":\"ios\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "null", false),
        ("SR-173", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"web\"}", true),
        ("SR-174", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"web\"}", false),
        ("SR-175", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"screen_name\",\"op\":\"neq\",\"value\":\"Cart\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"screen_name\":\"\"}", true),
        ("SR-176", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"screen_name\",\"op\":\"exists\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"screen_name\":\"\"}", false),
        ("SR-177", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"lt\",\"value\":\"2.10\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.3.1\"}", true),
        ("SR-178", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gt\",\"value\":\"9.9.9\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"10.0\"}", true),
        ("SR-179", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gt\",\"value\":\"2.0.10\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.1.0\"}", true),
        ("SR-180", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"eq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.3.0\"}", true),
        ("SR-181", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"eq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"v2.3.0.0\"}", true),
        ("SR-182", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.4.0-beta\"}", false),
        ("SR-183", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.4.0-beta\"}", false),
        ("SR-184", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.4.0-beta\"}", false),
        ("SR-185", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.4.0-beta\"}", true),
        ("SR-186", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.3\\n\"}", true),
        ("SR-187", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.3\\n\"}", false),
        ("SR-188", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.3\\n\"}", false),
        ("SR-189", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.3\\n\"}", true),
        ("SR-190", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"２.３\"}", false),
        ("SR-191", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"２.３\"}", false),
        ("SR-192", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"２.３\"}", false),
        ("SR-193", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"２.３\"}", true),
        ("SR-194", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"+1\"}", false),
        ("SR-195", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"+1\"}", false),
        ("SR-196", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"+1\"}", false),
        ("SR-197", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"+1\"}", true),
        ("SR-198", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"1.2.3.4.5\"}", false),
        ("SR-199", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"1.2.3.4.5\"}", false),
        ("SR-200", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"1.2.3.4.5\"}", false),
        ("SR-201", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"1.2.3.4.5\"}", true),
        ("SR-202", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"00000000001\"}", false),
        ("SR-203", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"00000000001\"}", false),
        ("SR-204", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"00000000001\"}", false),
        ("SR-205", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"00000000001\"}", true),
        ("SR-206", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\"}]}}", "purchase", "{\"app_version\":2.3}", nil, "null", false),
        ("SR-207", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\"}]}}", "purchase", "{\"app_version\":2.3}", nil, "null", false),
        ("SR-208", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\"}]}}", "purchase", "{\"app_version\":2.3}", nil, "null", false),
        ("SR-209", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\"}]}}", "purchase", "{\"app_version\":2.3}", nil, "null", true),
        ("SR-210", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"eq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", false),
        ("SR-211", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", true),
        ("SR-212", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", false),
        ("SR-213", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", true),
        ("SR-214", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gt\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", false),
        ("SR-215", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", false),
        ("SR-216", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"lt\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", false),
        ("SR-217", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"lte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", false),
        ("SR-218", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", false),
        ("SR-219", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_exists\",\"value\":true,\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"ios\"}", true),
        ("SR-220", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"eq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", false),
        ("SR-221", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", true),
        ("SR-222", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", false),
        ("SR-223", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", true),
        ("SR-224", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gt\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", false),
        ("SR-225", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"gte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", false),
        ("SR-226", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"lt\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", false),
        ("SR-227", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"lte\",\"value\":\"2.3\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", false),
        ("SR-228", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"exists\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", false),
        ("SR-229", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_exists\",\"value\":true,\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"\"}", true),
        ("SR-230", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"in\",\"value\":\"[\\\"2.10\\\",\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.3.0\"}", true),
        ("SR-231", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.10\\\",\\\"2.3\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"app_version\":\"2.3.0\"}", false),
        ("SR-232", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"build\",\"op\":\"gt\",\"value\":\"2.9\",\"type\":\"version\"}]}}", "purchase", "{\"build\":\"2.10\"}", nil, "null", true),
        ("SR-233", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"neq\",\"value\":\"2.4.0-beta\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"web\"}", false),
        ("SR-234", "{\"surface\":\"overlay\",\"layout\":\"modal\",\"trigger\":{\"kind\":\"event\",\"event_name\":\"purchase\",\"filters\":[{\"key\":\"app_version\",\"op\":\"not_in\",\"value\":\"[\\\"2.3\\\",\\\"beta\\\"]\",\"type\":\"version\",\"source\":\"dimension\"}]}}", "purchase", "{}", nil, "{\"platform_type\":\"web\"}", false),
        ]

        var disagreements: [String] = []
        for (id, contentJSON, event, propertiesJSON, screen, dimensionsJSON, expected) in vectors {
            guard let content = try? JSONDecoder().decode(InAppContent.self, from: Data(contentJSON.utf8)) else {
                print("SHOWRULE \(id) false")
                if expected == true { disagreements.append("\(id): false, the reference records true") }
                continue
            }
            let properties = (try JSONSerialization.jsonObject(with: Data(propertiesJSON.utf8)))
                as? [String: Any] ?? [:]
            let dimensions = (try JSONSerialization.jsonObject(
                with: Data(dimensionsJSON.utf8), options: [.fragmentsAllowed]
            )) as? [String: Any]

            let answer = inAppTriggerMatches(
                content.trigger,
                eventName: event,
                properties: properties,
                screenName: screen,
                dimensions: dimensions
            )

            print("SHOWRULE \(id) \(answer)")
            if let expected, answer != expected {
                disagreements.append("\(id): \(answer), the reference records \(expected)")
            }
        }

        XCTAssertTrue(
            disagreements.isEmpty,
            "The filter half disagrees with the reference's recorded answer:\n" + disagreements.joined(separator: "\n")
        )
    }
}
